var hierarchy =
[
    [ "Thoth::NJson::Details::BufferInfo", "struct_thoth_1_1_n_json_1_1_details_1_1_buffer_info.html", null ],
    [ "Thoth::String::CharSequences", "struct_thoth_1_1_string_1_1_char_sequences.html", null ],
    [ "Thoth::Http::Client", "struct_thoth_1_1_http_1_1_client.html", null ],
    [ "Thoth::Http::ClientJanitor", "struct_thoth_1_1_http_1_1_client_janitor.html", null ],
    [ "Thoth::Http::ConnectMethod", "struct_thoth_1_1_http_1_1_connect_method.html", null ],
    [ "Thoth::Dsa::Cow< RefT, OwnT >", "struct_thoth_1_1_dsa_1_1_cow.html", null ],
    [ "Thoth::Http::DeleteMethod", "struct_thoth_1_1_http_1_1_delete_method.html", null ],
    [ "Thoth::Dsa::FileBuilderParams", "struct_thoth_1_1_dsa_1_1_file_builder_params.html", null ],
    [ "Thoth::Dsa::FileOutputRange< T >", "struct_thoth_1_1_dsa_1_1_file_output_range.html", null ],
    [ "Thoth::Http::GenericError", "struct_thoth_1_1_http_1_1_generic_error.html", null ],
    [ "Thoth::Http::GetMethod", "struct_thoth_1_1_http_1_1_get_method.html", null ],
    [ "Thoth::Http::Headers", "struct_thoth_1_1_http_1_1_headers.html", null ],
    [ "Thoth::Http::HeadMethod", "struct_thoth_1_1_http_1_1_head_method.html", null ],
    [ "Thoth::String::CharSequences::Http", "struct_thoth_1_1_string_1_1_char_sequences_1_1_http.html", null ],
    [ "Thoth::Http::Client::HttpData< Body >", "struct_thoth_1_1_http_1_1_client_1_1_http_data.html", null ],
    [ "Thoth::Http::NHeaders::InvalidHeaderFormat", "struct_thoth_1_1_http_1_1_n_headers_1_1_invalid_header_format.html", null ],
    [ "Thoth::String::UnicodeViewer< CharT >::Iterator", "struct_thoth_1_1_string_1_1_unicode_viewer_1_1_iterator.html", null ],
    [ "Thoth::Utils::SharedInputView< Range >::Iterator", "struct_thoth_1_1_utils_1_1_shared_input_view_1_1_iterator.html", null ],
    [ "Thoth::NJson::Json", "struct_thoth_1_1_n_json_1_1_json.html", null ],
    [ "Thoth::Http::JsonFindError", "struct_thoth_1_1_http_1_1_json_find_error.html", null ],
    [ "Thoth::Http::JsonGetError", "struct_thoth_1_1_http_1_1_json_get_error.html", null ],
    [ "Thoth::NJson::JsonObject", "struct_thoth_1_1_n_json_1_1_json_object.html", null ],
    [ "Thoth::Http::JsonParseError", "struct_thoth_1_1_http_1_1_json_parse_error.html", null ],
    [ "Thoth::Http::JsonSearchError", "struct_thoth_1_1_http_1_1_json_search_error.html", null ],
    [ "Thoth::Http::JsonWrongTypeError", "struct_thoth_1_1_http_1_1_json_wrong_type_error.html", null ],
    [ "Thoth::Dsa::LinearMap< KeyT, ValT, Pred >", "struct_thoth_1_1_dsa_1_1_linear_map.html", null ],
    [ "Thoth::Dsa::LinearMap< JsonObjKey, Json >", "struct_thoth_1_1_dsa_1_1_linear_map.html", null ],
    [ "Thoth::Dsa::LinearMap< QueryKey, QueryValues >", "struct_thoth_1_1_dsa_1_1_linear_map.html", null ],
    [ "Thoth::Http::NHeaders::ListProxy< T, IsConst >", "struct_thoth_1_1_http_1_1_n_headers_1_1_list_proxy.html", null ],
    [ "Thoth::Http::NHeaders::MimeType", "struct_thoth_1_1_http_1_1_n_headers_1_1_mime_type.html", null ],
    [ "Thoth::Http::NHeaders::MimeTypes", "struct_thoth_1_1_http_1_1_n_headers_1_1_mime_types.html", null ],
    [ "Thoth::Http::OptionsMethod", "struct_thoth_1_1_http_1_1_options_method.html", null ],
    [ "Thoth::Http::PatchMethod", "struct_thoth_1_1_http_1_1_patch_method.html", null ],
    [ "Thoth::Http::PostMethod", "struct_thoth_1_1_http_1_1_post_method.html", null ],
    [ "Thoth::Http::PutMethod", "struct_thoth_1_1_http_1_1_put_method.html", null ],
    [ "Thoth::Http::QueryParams", "struct_thoth_1_1_http_1_1_query_params.html", null ],
    [ "Thoth::Http::Request< Method, Body >", "struct_thoth_1_1_http_1_1_request.html", null ],
    [ "Thoth::Http::Response< Method, Body >", "struct_thoth_1_1_http_1_1_response.html", null ],
    [ "Thoth::Utils::SharedInputView< Range >", "struct_thoth_1_1_utils_1_1_shared_input_view.html", null ],
    [ "Thoth::Http::Socket", "struct_thoth_1_1_http_1_1_socket.html", null ],
    [ "Thoth::NJson::StringRef", "struct_thoth_1_1_n_json_1_1_string_ref.html", null ],
    [ "Thoth::Http::TraceMethod", "struct_thoth_1_1_http_1_1_trace_method.html", null ],
    [ "Thoth::String::UnicodeViewer< CharT >", "struct_thoth_1_1_string_1_1_unicode_viewer.html", null ],
    [ "Thoth::Http::NHeaders::Upgrade", "struct_thoth_1_1_http_1_1_n_headers_1_1_upgrade.html", null ],
    [ "Thoth::Http::Url", "struct_thoth_1_1_http_1_1_url.html", null ],
    [ "Thoth::Http::NHeaders::ValueProxy< T, IsConst >", "struct_thoth_1_1_http_1_1_n_headers_1_1_value_proxy.html", null ],
    [ "std::variant", null, [
      [ "Thoth::Http::RequestError", "struct_thoth_1_1_http_1_1_request_error.html", null ]
    ] ],
    [ "Thoth::Utils::Ts", null, [
      [ "Thoth::Utils::Overloaded< Ts >", "struct_thoth_1_1_utils_1_1_overloaded.html", null ]
    ] ]
];